name: Build

on:
  push:
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install tox
        run: |
          pip install --upgrade pip
          pip install tox
      - name: Run tox for lint
        run: |
          tox -e lint
